/* Generated by Together */

#ifndef CONCRETEOBSERVER_H
#define CONCRETEOBSERVER_H

#include <iostream>
#include <string>

using namespace std;

// Die Concreten Observer sind vollständig unabhängig vom Observer
// sie sind nicht von Observer abgeleitet, sondern werden durch den
// "Kit" mit der Anwendung miteinander verbunden

class ConcreteObserver1 {
public:    
	ConcreteObserver1(string name);
	virtual ~ConcreteObserver1();
	void update(string& subjectName, int callCount);
	void operation1(string& subjectName, int callCount);
	void operation2(string& subjectName, int callCount);
	void operation3(string& subjectName, int callCount);
private:
	string name;
	static int objectCount;
};

class ConcreteObserver2 {
public:   
	ConcreteObserver2(string name);
	virtual ~ConcreteObserver2();
	void update(string& subjectName, int callCount);
private:

	string name;
	static int objectCount;
};

#endif //CONCRETEOBSERVER_H
