/* Generated by Together */

#ifndef CONCRETEOBSERVER_H
#define CONCRETEOBSERVER_H

#include <string>

// Die Concreten Observer sind vollständig unabhängig vom Observer
// sie sind nicht von Observer abgeleitet, sondern werden durch den
// "Kit" mit der Anwendung miteinander verbunden

class ConcreteObserver1 {
public:    
	ConcreteObserver1(std::string name);
	virtual ~ConcreteObserver1();
	void update(std::string& subjectName, int callCount);
	void operation1(std::string& subjectName, int callCount);
	void operation2(std::string& subjectName, int callCount);
	void operation3(std::string& subjectName, int callCount);
private:
	std::string name;
	static int objectCount;
};

class ConcreteObserver2 {
public:   
	ConcreteObserver2(std::string name);
	virtual ~ConcreteObserver2();
	void update(std::string& subjectName, int callCount);
private:

	std::string name;
	static int objectCount;
};

#endif //CONCRETEOBSERVER_H
